(TeX-add-style-hook "JazzPomfrit"
 (lambda ()
    (TeX-add-symbols
     '("stext" 1)
     "ORIincludegraphics")
    (TeX-run-style-hooks
     "autonum"
     "cleveref"
     "noabbrev"
     "hyperref"
     "calc"
     "listliketab"
     "siunitx"
     "natbib"
     "square"
     "sort"
     "comma"
     "numbers"
     "nomencl"
     "subcaption"
     "titlesec"
     "placeins"
     "graphicx"
     "soul"
     "mhchem"
     "luatextra"
     "unicode-math"
     "lmodern"
     "fontenc"
     "T1"
     "inputenc"
     "utf8"
     "iftex"
     "empheq"
     "amsmath"
     "latex2e"
     "memoir11"
     "memoir"
     "english"
     "a4paper"
     "twoside"
     "article"
     "11pt"
     "JazzPomfrit_frontpage"
     "JazzPomfrit_indledning"
     "JazzPomfrit_MaterialsAndMethods"
     "JazzPomfrit_ResultsAndDiscussion")))

