(TeX-add-style-hook "teori"
 (lambda ()
    (LaTeX-add-labels
     "sec:tsl"
     "eq:hamilton"
     "eq:schr"
     "sec:losning"
     "eq:sum"
     "sec:ortsums"
     "eq:628"
     "eq:vmn"
     "sec:kvantespring"
     "eq:Vext"
     "eq:mpb"
     "eq:2sch"
     "eq:2schb"
     "eq:V1221"
     "eq:konventioner"
     "eq:diff1"
     "eq:cdiff"
     "eq:cdiff1"
     "eq:cdiff2"
     "sec:udledning"
     "eq:c2"
     "eq:c1"
     "sec:matrixrap"
     "sec:basisvektorer"
     "sec:grundtilstanden"
     "alphares1"
     "sec:eksciteret")))

